### ISSUE TITLE
The NOTICE.txt has removed the TrendMicro copyright

### ISSUE THREAD

**Issue by jonjoliver** [idealista/tlsh#4]
Hi

I think it is fine for Idealista to copyright the new work.
But you have removed the TrendMicro copyright from the original work.
The original NOTICE.txt said
      "Copyright 2010-2014 Trend Micro

   This product includes software developed at
    Trend Micro (http://www.trendmicro.com/)"

Please add this to the NOTICE.txt

Cheers
jono

**Comment by dortegau** [comment]
done, thanks for your feedback 👍
